apiVersion: apps/v1
kind: Deployment
metadata:
  name: korki
  labels:
    app: korki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korki
  template:
    metadata:
      labels:
        app: korki
