apiVersion: v1
kind: Secret
metadata:
    name: unifi-db-credentials
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WjS14JQ=,iv:l6tcqhOSWXjrC7yMIg0poDYqKRP92fhVcZ+nzrJ0p0g=,tag:Zg10DbEcUwKc8SPSz68q+A==,type:str]
    password: ENC[AES256_GCM,data:IgSVYbAQCupY3SqvLQ==,iv:CvL5vzGwEXSDQ7LydIM47HP62IHBN3F8ifpLM+rfXb4=,tag:FyMbfBAu5e5cIPwu457L1g==,type:str]
sops:
    age:
        - recipient: age1905yh6x5l3p8g455ny20hr58y6pxla93q3xx74glwekn029phfkskv737g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWkpTb2ZYUFVEdi8yejFZ
            MTJIWTZ5dDlacjR3bmpialdhOWtyc1RzbmxRCjRRR0VsQVY1K3VlSHUzN2NZcXVZ
            bUgxb1djOVNERkpoNFlqTDFKU0Y1ZGsKLS0tIDJRMjNzWlZQdVlTTnFrTkNvNktG
            ZjdtclIxS2NmTUNOemNPc0tZV3lTdDgKvtMuJoLHE4URGFMR2unHS8mD9oIMTthF
            bC+y5rH7VdobG9M9+D64hbERLK7k6n4U0BeU7WW936xSnxwrzWtDYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:22:11Z"
    mac: ENC[AES256_GCM,data:JIhJOBppJG5+1JQUbmVXLe36/YustmYNZXMFdZy3EWKh1kbtVW+BSGKg5XyAHCvmFrRWh/Jg3fld1gcs5XF8FO3NPHd2/Z75/5JCIBlexbT9fhRCiNs2Lg4jK4I8D1t1uDan56mIsoHa+m+XRWYxaDFBOizP6QrZmKRSGmdBrd8=,iv:tBkGouDc8GWYlOBgVswjlzo/DgudxemcirbTtKDa3cE=,tag:gZAI7rOdoKZ6qk5woAsUqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
