# apiVersion: cdi.kubevirt.io/v1beta1
# kind: DataVolume
# metadata:
#   name: iso-ubuntu-direct
#   namespace: default
# spec:
#   source:
#     http:
#       url: "http://ftp.icm.edu.pl/pub/Linux/ubuntu-releases/22.04/ubuntu-22.04.5-live-server-amd64.iso"
#
#   storage:
#     accessModes:
#       - ReadWriteOnce
#     resources:
#       requests:
#         storage: 5Gi
# ---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-system
  namespace: default
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-pobierajaca-iso
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-vm
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        devices:
          autoattachGraphicsDevice: true
          disks:
            - name: dysk-glowny
              bootOrder: 1
              disk:
                bus: virtio

      volumes:
        - name: dysk-glowny
          dataVolume:
            name: ubuntu-system
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-vm-access
  namespace: default
spec:
  type: NodePort
  selector:
    kubevirt.io/vm: ubuntu-vm
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
