apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: iso-ubuntu-direct
  namespace: default
spec:
  source:
    http:
      url: "https://releases.ubuntu.com/jammy/ubuntu-22.04.5-live-server-amd64.iso"

  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-system
  namespace: default
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-pobierajaca-iso
  namespace: default
spec:
  running: true
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        devices:
          disks:
            - name: instalator
              bootOrder: 1
              cdrom:
                bus: sata
            - name: dysk-glowny
              bootOrder: 2
              disk:
                bus: virtio

      volumes:
        - name: instalator
          dataVolume:
            name: iso-ubuntu-direct
        - name: dysk-glowny
          dataVolume:
            name: ubuntu-system
