apiVersion: v1
kind: Secret
metadata:
    name: samba-credentials
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:T1TW02I=,iv:pNWbiQiJAS6Uk15EoOkWMdj8BtwRwp1Vs1dj4T3uTlg=,tag:rKeF3hC5Eq141A7tCHRe6g==,type:str]
    password: ENC[AES256_GCM,data:02qQy48EpZNfoQ==,iv:5wIVK5EJ9Dhz13y8gb6SR/bcr1zlMhWB05luPFj6XCw=,tag:kxKNquGuGjhx9r+Ki4D21A==,type:str]
sops:
    age:
        - recipient: age1905yh6x5l3p8g455ny20hr58y6pxla93q3xx74glwekn029phfkskv737g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMmVmUnZNaXFYNXNmR3J0
            YlVvaE11cVdteDZmVWd6TVhaa2NBQlVwNkUwCjRRNEV1MFRpcGcxSG1qd3VHazVy
            OHBrdDkwSEJ5TjN6NTJnV1h5ZGhUbnMKLS0tIDBWWXo5NWkzbWU4ZVF2Wkd3K3Ey
            eEtONGZYZlRhSndGeXpneUZOdzUyR1EK7r1Xr6jcaEt9f9XhZF5yD/da3F1Y68sB
            fnsYJQHtsGvo8VY2fIZdP6onH6r/y8cp7dBaSJutG5g9frkf5W+tcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T16:21:13Z"
    mac: ENC[AES256_GCM,data:BRd6A1rVQNTti1Jj7devxmpnEhTChdWZ2MqN0LhlD1CZERusF8q6ba8fm2Vz3DW8VcQ+dur7P3KqEs/5tETLJue1lDaN66/1CcxiaAylvkTpuW1NRA+N3zLa+kyrpHR0IGtOfKITQFPqCMjXKOSA41QchbPn2llLtqVgYR9sM74=,iv:NXLCAhhxOcJrQIwoKBGt5TpSLVewRH8llpvdIfk6IWQ=,tag:V9lPw8oLp3iBj8rcT0qxlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
